steps:
  - label: "Build and Push Docker Image"
    plugins:
      - docker#v3.8.0:
          image: "docker:latest"
          mount-buildkite-agent: true
          volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
          environment:
            - "DOCKER_LOGIN_USER"
            - "DOCKER_LOGIN_PASSWORD"
          commands:
            - "docker login -u $DOCKER_LOGIN_USER -p $DOCKER_LOGIN_PASSWORD"
            - "docker build -t evilgenius13/axiomstarfire:latest ."
            - "docker push evilgenius13/axiomstarfire:latest"