steps:
  - label: ":hammer: Build and Push"
    command: "scripts/build-and-push.sh"

  - wait

  - label: ":rocket: Deploy"
    command: "echo 'Add deployment script here'"
  
  - wait

  - label: ":discord: Notify on Success"
    command: "scripts/notify-discord-success.sh"
    # if: build.state == "passed"
    env:
      DISCORD_WEBHOOK_URL: "$DISCORD_WEBHOOK_URL"

  - label: ":large_orange_circle: Notify on Failure"
    command: "scripts/notify-discord-failure.sh"
    if: build.state == "failed"
    env:
      DISCORD_WEBHOOK_URL: "$DISCORD_WEBHOOK_URL"
